routes/admin.php
<?php

use Illuminate\Support\Facades\Route;


Route::group(['middleware'=>['guest:admin'],'as'=>'admin.'],function (){
    Route::get('/login', 'Auth\LoginController@create')->name('login');
    Route::post('/login', 'Auth\LoginController@store')->name('login.store');
});


Route::group(['middleware'=>['auth:admin'],'as'=>'admin.'],function (){
    Route::post('/logout', 'Auth\LoginController@destroy')->name('logout');
    Route::get('/','HomeController@index')->name('home');
    Route::resource('supervisor','SupervisorController');
    Route::delete('delete-selected/supervisor','SupervisorController@delete_selected')->name('supervisor.delete_selected');
    Route::patch('active-toggle/supervisor/{supervisor}','SupervisorController@activeToggle')->name('supervisor.activeToggle');
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';

app/Models/Supervisor.php
<?php

namespace App\Models;

use App\Http\Traits\FilesAttributes;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Laravel\Sanctum\HasApiTokens;

class Supervisor extends Authenticatable
{
    use HasFactory,HasApiTokens,SoftDeletes,FilesAttributes;

    protected $folder = 'supervisor';
    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name', 'email', 'password', 'phone', 'is_active', 'avatar',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function setPasswordAttribute($value){
        if($value)
            $this->attributes['password'] = bcrypt($value);
    }
}

app/Http/Controllers/Admin/SupervisorController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\SupervisorRequest;
use App\Models\Supervisor;
use Illuminate\Http\Request;

class SupervisorController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $supervisors = Supervisor::paginate(10);
        return view('admin.supervisor.index',compact('supervisors'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.supervisor.add');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  SupervisorRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(SupervisorRequest $request)
    {
        $inputs = $request->except(['_token']);
        $inputs['is_active'] = 1;
        Supervisor::create($inputs);
        return redirect()->route('admin.supervisor.index')->with('success',__('added successfully'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Supervisor  $supervisor
     * @return \Illuminate\Http\Response
     */
    public function show(Supervisor $supervisor)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Supervisor  $supervisor
     * @return \Illuminate\Http\Response
     */
    public function edit(Supervisor $supervisor)
    {
        return  view('admin.supervisor.edit',compact('supervisor'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  SupervisorRequest  $request
     * @param  \App\Models\Supervisor  $supervisor
     * @return \Illuminate\Http\Response
     */
    public function update(SupervisorRequest $request, Supervisor $supervisor)
    {
        $supervisor->update($request->except(['_token','_method']));
        return redirect()->route('admin.supervisor.index')->with('success',__('updated successfully'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Supervisor  $supervisor
     * @return \Illuminate\Http\Response
     */
    public function destroy(Supervisor $supervisor)
    {
        $supervisor->delete();
        return response()->json(['status'=>true,'message'=>__('deleted successfully')],200);
    }

    /**
     * @param Request $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function delete_selected(Request $request){
        Supervisor::whereIn('id',$request['ids'])->delete();
        return response()->json(['status'=>true,'message'=>__('deleted successfully')],200);
    }
    public function activeToggle(Supervisor $supervisor){
        if($supervisor->is_active){
            $supervisor->update(['is_active'=>0]);
            return response()->json(['status'=>true,'message'=>__('supervisor deactivate'),'flag'=>0],200);
        }else{
            $supervisor->update(['is_active'=>1]);
            return response()->json(['status'=>true,'message'=>__('supervisor activate'),'flag'=>1],200);
        }

    }
}

app/Http/Controllers/Supervisor/CategoriesController.php
<?php

namespace App\Http\Controllers\Supervisor;

use App\Http\Controllers\Controller;
use App\Http\Requests\Supervisor\CategoriesRequest;
use App\Models\Category;
use Illuminate\Http\Request;

class CategoriesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::paginate(10);
        return view('supervisor.categories.index',compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('supervisor.categories.add');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  CategoriesRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CategoriesRequest $request)
    {
        Category::create($request->except(['_token']));
        return redirect()->route('supervisor.categories.index')->with('success',__('added successfully'));
    }

    /**
     * Display the specified resource.
     *
     * @param  Category $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  Category $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        return  view('supervisor.categories.edit',compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  CategoriesRequest  $request
     * @param  Category $category
     * @return \Illuminate\Http\Response
     */
    public function update(CategoriesRequest $request, Category $category)
    {
        $category->update($request->except(['_token','_method']));
        return redirect()->route('supervisor.categories.index')->with('success',__('updated successfully'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  Category $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        $category->delete();
        return response()->json(['status'=>true,'message'=>__('deleted successfully')],200);
    }

    /**
     * @param Request $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function delete_selected(Request $request){
        Category::whereIn('id',$request['ids'])->delete();
        return response()->json(['status'=>true,'message'=>__('deleted successfully')],200);
    }


}

app/Http/Controllers/Supervisor/HomeController.php
<?php

namespace App\Http\Controllers\Supervisor;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    public function index(){
        return view('supervisor.layouts.main');
    }
}

app/Http/Controllers/Supervisor/ProductsController.php
<?php

namespace App\Http\Controllers\Supervisor;

use App\Http\Controllers\Controller;
use App\Http\Requests\Supervisor\ProductsRequest;
use App\Models\Product;
use App\Models\ProductImage;
use Illuminate\Http\Request;

class ProductsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::paginate(10);
        return view('supervisor.products.index',compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('supervisor.products.add');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  ProductsRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProductsRequest $request)
    {
        $product = Product::create($request->except(['_token','images']));
        if($request->has('images')){
            multiUploader($request,'images','product_images/'.date('Y-m'),new ProductImage(),$product->id);
        }
        return redirect()->route('supervisor.products.index')->with('success',__('added successfully'));
    }

    /**
     * Display the specified resource.
     *
     * @param  Product $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        return  view('supervisor.products.show',compact('product'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  Product $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        return  view('supervisor.products.edit',compact('product'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param ProductsRequest  $request
     * @param  Product $product
     * @return \Illuminate\Http\Response
     */
    public function update(ProductsRequest $request, Product $product)
    {
        $product->update($request->except(['_token','_methods','images']));
        if($request->has('images')) {
            multiUploader($request, 'images', 'product_images/' . date('Y-m'), new ProductImage(), ['product_id'=>$product->id]);
        }
        return redirect()->route('supervisor.products.index')->with('success',__('updated successfully'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  Product $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        $product->delete();
        return response()->json(['status'=>true,'message'=>__('deleted successfully')],200);
    }

    /**
     * @param Request $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function delete_selected(Request $request){
        Product::whereIn('id',$request['ids'])->delete();
        return response()->json(['status'=>true,'message'=>__('deleted successfully')],200);
    }

    public function imgDelete($id){
        $product_image = ProductImage::findOrFail($id);
        $product = $product_image->product;
        $product_image->delete();

        return redirect()->route('supervisor.products.show',compact('product'))->with('success',__('deleted successfully'));
    }
}

resources/views/admin/supervisor/add.blade.php
@extends('admin.layouts.app')
@section('title' , 'بيانات المشرف')
@section('styles')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fontawesome-iconpicker/3.2.0/css/fontawesome-iconpicker.min.css"/>
@endsection
@section('breadcrumb')
    @php
        $routes =  [
            ['route'=>route('admin.supervisor.index'),'name'=>'المشرفين']
        ];
    @endphp
    @include('admin.layouts.page-breadcrumb',$routes)
@endsection
@section('content')
    {!! Form::open(['route' => 'admin.supervisor.store','method'=>'post','class'=>'form-horizontal','files'=>true]) !!}
        @include('admin.supervisor.form')
    {!! Form::close() !!}
@endsection
@section('scripts')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fontawesome-iconpicker/3.2.0/js/fontawesome-iconpicker.min.js"></script>
    <script>
        $('.demo').iconpicker();
        $('.dropdown-menu').on('click','a',function (){
            $('#icon').val($(this).attr('title').replace('.','')??'')
        })
    </script>
@endsection

resources/views/admin/supervisor/edit.blade.php
@extends('admin.layouts.app')
@section('title' , 'بيانات المشرف')
@section('styles')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fontawesome-iconpicker/3.2.0/css/fontawesome-iconpicker.min.css"/>
@endsection
@section('breadcrumb')
    @php
        $routes =  [
            ['route'=>route('admin.supervisor.index'),'name'=>'المشرفين']
        ];
    @endphp
    @include('admin.layouts.page-breadcrumb',$routes)
@endsection
@section('content')
    {!! Form::model($supervisor,['route' =>['admin.supervisor.update',$supervisor->id],'method'=>'put','class'=>'form-horizontal','files'=>true]) !!}
        @include('admin.supervisor.form')
    {!! Form::close() !!}
@endsection
@section('scripts')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fontawesome-iconpicker/3.2.0/js/fontawesome-iconpicker.min.js"></script>

    <script>
        $('.demo').iconpicker();
        $('.dropdown-menu').on('click','a',function (){
            $('#icon').val($(this).attr('title').replace('.','')??'')
        })
    </script>
@endsection

resources/views/admin/supervisor/form.blade.php
<div class="row">
    <!-- column -->
    <div class="col-lg-12">
        <div class="card">
            <div class="card-body box bg-cyan ">
                <h4 class="card-title text-white">بيانات المشرف</h4>
            </div>
            <div class="comment-widgets">
                <div class="card-body">
                    <div class="form-group row">
                        <label for="name" class="col-sm-1 text-right control-label col-form-label">الاسم </label>
                        <div class="col-sm-5">
                            {!! Form::text('name',null,['class' =>'form-control '.($errors->has('name') ? ' is-invalid' : null),'placeholder'=> 'الاسم ','id'=>'name' ]) !!}
                            @error('name')
                            <span class="invalid-feedback">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>

                        <label for="email" class="col-sm-1 text-left control-label col-form-label">الايميل  </label>
                        <div class="col-sm-5">
                            {!! Form::email('email',null,['class' =>'form-control '.($errors->has('email') ? ' is-invalid' : null),'placeholder'=> 'الايميل','id'=>'email' ]) !!}
                            @error('email')
                            <span class="invalid-feedback">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="phone" class="col-sm-1 text-right control-label col-form-label">الهاتف </label>
                        <div class="col-sm-5">
                            {!! Form::tel('phone',null,['class' =>'form-control '.($errors->has('phone') ? ' is-invalid' : null),'placeholder'=> 'الهاتف ','id'=>'phone' ]) !!}
                            @error('phone')
                            <span class="invalid-feedback">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>

                        <label for="avatar" class="col-sm-1 text-left control-label col-form-label">الصورة </label>
                        <div class="col-sm-3">
                            {!! Form::file('avatar',['class'=>'form-control '.($errors->has('avatar') ? ' is-invalid' : null),'id'=>'avatar']) !!}
                            @error('avatar')
                            <span class="invalid-feedback display-img-validation">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                        <div class="col-sm-2">
                            <img src="{{isset($supervisor)?$supervisor->avatar:asset('_admin/assets/images/user.jpg')}}" alt="user" class="img-thumbnail" height="70" width="70">
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="password" class="col-sm-1 text-right control-label col-form-label">كلمة المرور </label>
                        <div class="col-sm-5">
                            {!! Form::password('password',['class' =>'form-control '.($errors->has('password') ? ' is-invalid' : null),'placeholder'=> 'كلمة المرور  ','id'=>'password' ]) !!}
                            @error('password')
                            <span class="invalid-feedback">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>

                        <label for="password_confirmation" class="col-sm-1 text-left control-label col-form-label">تاكيد كلمة المرور  </label>
                        <div class="col-sm-5">
                            {!! Form::password('password_confirmation',['class' =>'form-control '.($errors->has('password_confirmation') ? ' is-invalid' : null),'placeholder'=> 'تاكيد كلمة المرور  ','id'=>'password_confirmation' ]) !!}
                            @error('password_confirmation')
                            <span class="invalid-feedback">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>

                </div>
            </div>
        </div>


    </div>


</div>
<div class="border-top">
    <div class="card-body text-center">
        <button type="submit" class="btn btn-primary">تأكيد</button>
    </div>
</div>

resources/views/admin/supervisor/index.blade.php
@extends('admin.layouts.app')
@section('title' , 'كل المشرفين')
@section('styles')
    <style>
        .active{
            color: gold;
        }
        .inactive{
            color: #0b0b0b;
        }
    </style>
@endsection
@section('breadcrumb')
    @php
        $routes =  [];
    @endphp
    @include('admin.layouts.page-breadcrumb',$routes)
@endsection
@section('content')
    <div class="row">
        <!-- column -->
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body box bg-cyan ">
                    <h4 class="card-title text-white">كل المشرفين</h4>
                </div>
                <div class="border-bottom">
                    <div class="card-body">
                        <a href="{{route('admin.supervisor.create')}}" class="btn btn-info">إضافة مشرف</a>
                        <button data-action="{{route('admin.supervisor.delete_selected')}}" class="btn btn-danger" id="del-all">حذف المحدد</button>
                    </div>

                </div>
                <div class="accordion" id="accordionExample">
                    <div id="collapse1" class="collapse show" aria-labelledby="heading1" data-parent="#accordionExample">
                        <div class="card-body">
                            <table id="zero_config" class="table table-striped table-bordered">
                                <thead class="bg-cyan text-white">
                                <tr class="text-center">
                                    <th>#</th>
                                    <th>
                                        <input type="checkbox" name="select_all[]" id="select_all">
                                    </th>
                                    <th>الاسم</th>
                                    <th>الايميل</th>
                                    <th>الهاتف</th>
                                    <th>صورة</th>
                                    <th class="text-center">التحكم</th>
                                </tr>
                                </thead>
                                <tbody>
                                    @forelse($supervisors as $key => $supervisor)
                                        <tr class="text-center" id="row-{{$supervisor->id}}">
                                            <td>{{++$key}}</td>
                                            <td>
                                                <input type="checkbox" value="{{$supervisor->id}}" name="select_row[]" class="select_row">
                                            </td>
                                            <td>{{$supervisor->name}}</td>
                                            <td>{{$supervisor->email}}</td>
                                            <td>{{$supervisor->phone}}</td>
                                            <td>
                                                <img src="{{$supervisor->avatar}}" alt="{{$supervisor->name}}" class="img-thumbnail" height="70px" width="70px" loading="lazy">
                                            </td>

                                            <td class="text-center">
                                                <a href="{{route('admin.supervisor.edit',[$supervisor->id])}}" class="btn btn-outline-cyan btn-rounded btn-sm">
                                                    <i class="fas fa-edit"></i>
                                                </a>

                                                <button data-href="{{route('admin.supervisor.activeToggle',[$supervisor->id])}}" class="btn btn-outline-cyan btn-rounded btn-sm activeToggle">
                                                    <i class="fas fa-star {{$supervisor->is_active?'active':'inactive'}}" ></i>
                                                </button>
                                                <a class="btn btn-outline-danger btn-rounded btn-sm btnDelete"
                                                   data-id="{{$supervisor->id}}" id='delete-form{{$supervisor->id}}'
                                                   data-action="{{route('admin.supervisor.destroy',$supervisor->id)}}">
                                                    <i class="fas fa-trash"></i>
                                                </a>
                                            </td>
                                        </tr>
                                    @empty
                                    @endforelse
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="border-top">
                    <div class="card-body text-center">
                        {{$supervisors->links("pagination::bootstrap-4")}}
                    </div>
                </div>

            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script src="{{asset('adminpanel/assets/extra-libs/DataTables/datatables.min.js')}}"></script>
    <script>
        $('.table').DataTable({
            "bPaginate": false,
            "language": {
                "paginate": {
                    "previous": "السابق",
                    "next": "التالي",
                    "search": "البحث:",
                }
            },
            "oLanguage": {
                "sSearch": "البحث:",
            },
            stateSave: true
        });
        $('#zero_config_filter').parent().prev('div').remove();
    </script>
    <script>
        $(document).ready(function (){
            $('#select_all').click(function(event) {
                if(this.checked) {
                    // Iterate each checkbox
                    $('input[name^="select_row"]').each(function() {
                        this.checked = true;
                    });
                } else {
                    $('input[name^="select_row"]').each(function() {
                        this.checked = false;
                    });
                }
            });

            $('#del-all').click(function (){
                let ids = $('input[name^="select_row"]:checked').map((i,e)=>e.value).toArray();
                let url = $(this).data('action');
                if(ids.length) {
                    customSwal(ids, url);
                }else{
                    swal("تنبية!", "قم بتحديد العناصر اولا", "info");
                }
            })

            $('.btnDelete').click(function (){
                let id = $(this).data('id');
                let url = `/admin/supervisor/${id}`;
                customSwal(id,url,$(this));
            })
            $('.activeToggle').click(function (){
                let url = $(this).data('href');
                $.ajax({
                    url,
                    type:'PATCH',
                    headers: {'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')},
                    success:(data)=>{
                        if(data.status){
                            let El = $(this).find('i');
                            data.flag?El.removeClass('inactive').addClass('active'):El.removeClass('active').addClass('inactive');
                            swal('تم التعديل بنجاح',data.message,'success')
                        }
                    }
                })
            })
            function customSwal(id,url,el){
                swal({
                    title: "هل أنت متاكد",
                    text: "اذا تم الحذف لا يمكن الاستعادة مرة اخرى",
                    icon: "warning",
                    buttons: true,
                    dangerMode: true,
                }).then((willDelete) => {
                    if (willDelete) {
                        $.ajax({
                            url,
                            type:'DELETE',
                            data:{ids:id??''},
                            headers: {'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')},
                            success:(data)=>{
                                if(data.status){
                                    if(el!=null){
                                        el.closest('tr').remove();
                                    }else{
                                       id.map((i)=>{
                                           $(`#row-${i}`).remove();
                                       })
                                    }
                                    swal(data.message, {icon: "success"});
                                }

                            }
                        })
                    } else {
                        swal("تم الالغاء بنجاح !");
                    }
                });
            }
        })
    </script>
@endsection