routes/admin.php
<?php

use Illuminate\Support\Facades\Route;


Route::group(['middleware'=>['guest:admin'],'as'=>'admin.'],function (){
    Route::get('/login', 'Auth\LoginController@create')->name('login');
    Route::post('/login', 'Auth\LoginController@store')->name('login.store');
});


Route::group(['middleware'=>['auth:admin'],'as'=>'admin.'],function (){
    Route::post('/logout', 'Auth\LoginController@destroy')->name('logout');
    Route::get('/','HomeController@index')->name('home');
    Route::resource('supervisor','SupervisorController');
    Route::delete('delete-selected/supervisor','SupervisorController@delete_selected')->name('supervisor.delete_selected');
    Route::patch('active-toggle/supervisor/{supervisor}','SupervisorController@activeToggle')->name('supervisor.activeToggle');
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';

resources/views/admin/layouts/alert.blade.php

@if(Session::has('success'))
    <div class="alert alert-success alert-styled-left">
        <button type="button" class="close" data-dismiss="alert">
            <span>×</span>
            <span class="sr-only">Close</span>
        </button>
        {{ Session::get('success') }}
    </div>
@endif

@if(Session::has('alert'))
    <div class="alert alert-info alert-styled-left">
        <button type="button" class="close" data-dismiss="alert">
            <span>×</span>
            <span class="sr-only">Close</span>
        </button>
        {{ Session::get('alert') }}
    </div>
@endif

@if(Session::has('error'))
    <div class="alert alert-danger alert-styled-left d-block">
        <button type="button" class="close" data-dismiss="alert"><span>×</span><span class="sr-only">Close</span></button>
        {{ Session::get('error') }}
    </div>
@endif

@if (count($errors) > 0)
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

resources/views/admin/layouts/app.blade.php
<!DOCTYPE html>
<html dir="rtl" lang="ar">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" type="image/png" sizes="16x16" href="{{asset('_admin/assets/images/favicon.png')}}">
    <title> لوحة تحكم الموقع - @yield('title')</title>
    <link href="{{asset('_admin/assets/libs/flot/css/float-chart.css')}}" rel="stylesheet">
    <link href="{{asset('_admin/dist/css/style.min.css')}}" rel="stylesheet">
    <link href="{{asset('_admin/dist/css/style-rtl.css')}}" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{{ asset('_admin/assets/libs/quill/dist/quill.snow.css') }}">
    <meta name="csrf-token" content="{{csrf_token()}}">
    <style>
        .display-img-validation{
            display: block;
        }
        .btnDelete{
            text-decoration: none;
        }
        .btnDelete:hover{
            text-decoration: none;
            background: #fff;
            color: #da542e;
        }
        .btnDelete i{
            text-decoration: none;
            color: #da542e;
        }
        .btnDelete i:hover{
            text-decoration: none;
            color: #da542e;
        }
         #notyBtn1{
             margin: 4px;
         }
        #notyBtn2{
            margin: 4px;
        }

    </style>
    @yield('styles')
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>


<body>
<div class="preloader">
    <div class="lds-ripple">
        <div class="lds-pos"></div>
        <div class="lds-pos"></div>
    </div>
</div>
<div id="main-wrapper">
    <!-- ============================================================== -->
    <!-- Topbar header - style you can find in pages.scss -->
    <!-- ============================================================== -->


    @include('admin.layouts.header')

    @include('admin.layouts.sidebar')

    <div class="page-wrapper">
        @yield('breadcrumb')

        <div class="container-fluid">

        @include('admin.layouts.alert')
        @yield('content')

        </div>
        <footer class="footer text-center">
            جميع الحقوق محفوظة  <a href="#">للشركة</a> @ {{date('Y')}}.
        </footer>
    </div>
</div>
@include('admin.layouts.scripts')
</body>

</html>

resources/views/admin/layouts/header.blade.php
<header class="topbar" data-navbarbg="skin5">
    <nav class="navbar top-navbar navbar-expand-md navbar-dark">
        <div class="navbar-header" data-logobg="skin5">
            <!-- This is for the sidebar toggle which is visible on mobile only -->
            <a class="nav-toggler waves-effect waves-light d-block d-md-none" href="javascript:void(0)"><i class="ti-menu ti-close"></i></a>
            <!-- ============================================================== -->
            <!-- Logo -->
            <!-- ============================================================== -->
            <a class="navbar-brand" href="{{route('admin.home')}}">
                <span class="logo-text">
                    <!-- dark Logo text -->
                    <img src="{{asset('_admin/assets/images/logo-text.png')}}" alt="homepage" class="light-logo" />
                </span>
            </a>
            <!-- ============================================================== -->
            <!-- End Logo -->
            <!-- ============================================================== -->
            <!-- ============================================================== -->
            <!-- Toggle which is visible on mobile only -->
            <!-- ============================================================== -->
            <a class="topbartoggler d-block d-md-none waves-effect waves-light" href="javascript:void(0)" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><i class="ti-more"></i></a>
        </div>
        <!-- ============================================================== -->
        <!-- End Logo -->
        <!-- ============================================================== -->
        <div class="navbar-collapse collapse" id="navbarSupportedContent" data-navbarbg="skin5">
            <!-- ============================================================== -->
            <!-- toggle and nav items -->
            <!-- ============================================================== -->
            <ul class="navbar-nav float-left ml-auto">
                <li class="nav-item d-none d-md-block"><a class="nav-link sidebartoggler waves-effect waves-light" href="javascript:void(0)" data-sidebartype="mini-sidebar"><i class="mdi mdi-menu font-24"></i></a></li>
            </ul>
            <!-- ============================================================== -->
            <!-- Right side toggle and nav items -->
            <!-- ============================================================== -->
            <ul class="navbar-nav float-right">

                <!-- ============================================================== -->
                <!-- User profile and search -->
                <!-- ============================================================== -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle text-muted waves-effect waves-dark pro-pic" href="" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><img src="{{asset('_admin/assets/images/users/1.jpg')}}" alt="user" class="rounded-circle" width="31"></a>
                    <div class="dropdown-menu dropdown-menu-left user-dd animated">
                        <div class="dropdown-divider"></div>
                        @if(auth('admin')->check())
                        <div class="mx-2"><a href="{{ route('admin.logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();" class="btn btn-sm btn-warning btn-rounded"><i class="fa fa-power-off m-r-5 m-l-5"></i> تسجيل خروج</a>
                            <form id="logout-form" action="{{ route('admin.logout') }}" method="POST" class="d-none">
                                @csrf
                            </form>
                        </div>
                        @endif
                    </div>
                </li>
                <!-- ============================================================== -->
                <!-- User profile and search -->
                <!-- ============================================================== -->
            </ul>
        </div>
    </nav>
</header>

resources/views/admin/layouts/main.blade.php
@extends('admin.layouts.app')
@section('content')
<div class="row">
    <div class="col-md-6 col-lg-4 col-xl-3">
        <div class="card card-hover">
            <a href="#" class="box bg-cyan text-center d-block">
                <h1 class="font-light text-white"><i class="mdi mdi-human"></i></h1>
                <h6 class="text-white"><span class="text-white">المشرفين ( {{\App\Models\Supervisor::count()}} )</span></h6>
            </a>
        </div>
    </div>

    <div class="col-md-6 col-lg-4 col-xl-3">
        <div class="card card-hover">
            <a href="#" class="box bg-warning text-center d-block">
                <h1 class="font-light text-white"><i class="mdi mdi-chart-areaspline"></i></h1>
                <h6 class="text-white"><span class="text-white">قسم ( {{\App\Models\Category::count()}} )</span></h6>
            </a>
        </div>
    </div>

    <div class="col-md-6 col-lg-4 col-xl-3">
        <div class="card card-hover">
            <a href="#" class="box bg-info text-center d-block">
                <h1 class="font-light text-white"><i class="mdi mdi-blinds"></i></h1>
                <h6 class="text-white"><span class="text-white">منتج ( {{\App\Models\Product::count()}} )</span></h6>
            </a>
        </div>
    </div>

</div>

@endsection

resources/views/admin/layouts/page-breadcrumb.blade.php
<div class="page-breadcrumb">
    <div class="row">
        <div class="col-12 d-flex no-block align-items-center">
            <h4 class="page-title">لوحة التحكم</h4>
            <div class="mr-auto text-right">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{{route('admin.home')}}">الرئيسية</a></li>
                        @isset($routes)
                            @foreach($routes as $route)
                                <li class="breadcrumb-item"><a href="{{$route['route']}}">{{$route['name']}}</a></li>
                            @endforeach
                        @endisset
                        <li class="breadcrumb-item active" aria-current="page">@yield('title')</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>

resources/views/admin/layouts/scripts.blade.php
<script src="{{asset('_admin/assets/libs/jquery/dist/jquery.min.js')}}"></script>
<!-- Bootstrap tether Core JavaScript -->
<script src="{{asset('_admin/assets/libs/popper.js/dist/umd/popper.min.js')}}"></script>
<script src="{{asset('_admin/assets/libs/bootstrap/dist/js/bootstrap.min.js')}}"></script>
<script src="{{asset('_admin/assets/libs/perfect-scrollbar/dist/perfect-scrollbar.jquery.min.js')}}"></script>
<script src="{{asset('_admin/assets/extra-libs/sparkline/sparkline.js')}}"></script>
<!--Wave Effects -->
<script src="{{asset('_admin/dist/js/waves.js')}}"></script>
<!--Menu sidebar -->
<script src="{{asset('_admin/dist/js/sidebarmenu.js')}}"></script>
<!--Custom JavaScript -->
<script src="{{asset('_admin/dist/js/custom.min.js')}}"></script>
<!--This page JavaScript -->
<!-- <script src="{{asset('_admin/dist/js/pages/dashboards/dashboard1.js"></script> ')}}-->
<!-- Charts js Files -->
<script src="{{asset('_admin/assets/libs/flot/excanvas.js')}}"></script>
<script src="{{asset('_admin/assets/libs/flot/jquery.flot.js')}}"></script>
<script src="{{asset('_admin/assets/libs/flot/jquery.flot.pie.js')}}"></script>
<script src="{{asset('_admin/assets/libs/flot/jquery.flot.time.js')}}"></script>
<script src="{{asset('_admin/assets/libs/flot/jquery.flot.stack.js')}}"></script>
<script src="{{asset('_admin/assets/libs/flot/jquery.flot.crosshair.js')}}"></script>
<script src="{{asset('_admin/assets/libs/flot.tooltip/js/jquery.flot.tooltip.min.js')}}"></script>
<script src="{{asset('_admin/dist/js/pages/chart/chart-page-init.js')}}"></script>
<script src="{{asset('_admin/assets/libs/quill/dist/quill.min.js')}}"></script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
@if(session()->has('success'))
    <script>
        swal("أحسنت !", "{{session('success')}}", "success");
    </script>
@elseif(session()->has('error'))
    <script>
        swal("حدث خطاء ما !", "{{session('error')}}", "error");
    </script>
@endif
@yield('scripts')

resources/views/admin/layouts/sidebar.blade.php
<aside class="left-sidebar" data-sidebarbg="skin5">
    <!-- Sidebar scroll-->
    <div class="scroll-sidebar">
        <!-- Sidebar navigation-->
        <nav class="sidebar-nav">
            <ul id="sidebarnav" class="p-t-30">
                <li class="sidebar-item">
                    <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{{route('admin.home')}}" aria-expanded="false">
                        <i class="mdi mdi-view-dashboard"></i>
                        <span class="hide-menu">الرئيسية</span>
                    </a>
                </li>

                <li class="sidebar-item">
                    <a class="sidebar-link " href="{{route('admin.supervisor.index')}}">
                        <i class="mdi mdi-account-plus"></i>
                        <span class="hide-menu">المشرفين</span>
                    </a>
                </li>

            </ul>
        </nav>
        <!-- End Sidebar navigation -->
    </div>
    <!-- End Sidebar scroll-->
</aside>